### ISSUE TITLE
use bcftools to replace VT for left-normalization function

### ISSUE THREAD

**Issue by kaichop** [WangGenomicsLab/SeqMule#29]
Currently we are using VT solely for left-normalization yet this can be done just by vcftools/bcftools to reduce the number of external tools needed in SeqMule.

**Comment by yunfeiguo** [comment]
Sure.

**Comment by yunfeiguo** [comment]
left-normalization is only available in samtools 1.0+. I tested samtools 1.1 with seqmule and found there are incompatibilities (that are due to SAM/BAM format issue). Further investigation is needed.

**Comment by kaichop** [comment]
what kind of incompatibilities? This step is only for VCF files, not for BAM/SAM files.

**Comment by yunfeiguo** [comment]
normalization step is not available in old bcftools/samtools, so I have to
use SAMtools 1.1 here.

But I don't want to have two versions of SAMtools in SeqMule, so I tested
whether SAMtools 1.1 works with the entire pipeline.

The new SAMtools 1.1 cannot work with "bin/secondary/readFilter" for
unknown reason (it only complains parse error, but no more detail). Also,
SAMtools 1.1 doesn't have 'rmdup' function which I'm gonna use to replace
picard rmdup.

**Comment by yunfeiguo** [comment]
This issue will be postponed to the moment when samtools 1.1 works for seqmule.
