### ISSUE TITLE
multiple threads for freebayes

### ISSUE THREAD

**Issue by kaichop** [WangGenomicsLab/SeqMule#35]
it seems that freebayes variant calling is single thread only?

See https://github.com/ekg/freebayes/issues/73 for a simple solution to this problem, to accelerate the variant calling time.

**Comment by yunfeiguo** [comment]
Thanks for your suggestion.

Yes. I looked at Dr. Garrison's parallel solution (<a href="https://raw.githubusercontent.com/ekg/freebayes/master/scripts/freebayes-parallel">freebayes-parallel</a>). Basically, he uses GNU parallel to run freebayes over multiple regions in parallel. This is akin to running freebayes under seqmule's quick mode except that no temporary VCFs are created and that fork/waitpid is handled internally. So similar performance should be expected.
