### ISSUE TITLE
coverage figure looks suspicious

### ISSUE THREAD

**Issue by kaichop** [WangGenomicsLab/SeqMule#37]
my figure shows coverage axis range from 1 to 10,000. Perhaps it should be self-adjustable, so that the X for any Y<10% is not displayed. 

As a user, I want to see what's the fraction covered by 10 reads, 20 reads, 30 reads, etc.

**Comment by yunfeiguo** [comment]
The x-axis range is equal to [max(coverage),1]. y-axis range is equal to [0,1]. I can make a cutoff at 10% for y-axis, however, some information might be lost, e.g. unusually high coverage, is this okay?

fraction covered by 10,20 and 30 reads is shown in "coverage stats" table. Do you want to have it in coverage figure, too?

**Comment by kaichop** [comment]
I think you can generate two graphs with different scales.
