### ISSUE TITLE
disable File::Glob bsd_glob when it's not available

### ISSUE THREAD

**Issue by yunfeiguo** [WangGenomicsLab/SeqMule#61]
a couple of users have reported they don't have bsd_glob.

**Comment by yunfeiguo** [comment]
Problem: bsd_glob is not portable. bsd_glob and abs_path are used together to interpret the path (e.g. convert "~/projects/file.bam" to "/home/userid/projects/file.bam"), and resolve any relative path/symbolic link.

Solution: we need to find a PORTABLE way to interpret paths and resolve relative paths and symbolic links. What are the options?

**Comment by kaichop** [comment]
why do we need it? we can just get rid of it and ask people to type full path, not the "~" path

**Comment by yunfeiguo** [comment]
Sure. I just want to make seqmule more robust.
