### ISSUE TITLE
help message problem

### ISSUE THREAD

**Issue by kaichop** [WangGenomicsLab/SeqMule#70]
The help message is difficult to understand when running 'seqmule pipeline'. This should be changed to these situations below:

            #run analysis on paired end exome sequencing data. 
            seqmule pipeline -a s1.1.fastq -b s1.2.fastq -prefix exomeData -threads 12 -rg READGROUP -e -advanced misc/predefined_config/bwa_gatk.config -capture SureSelect_v4.bed

            #same as above except that the data comes from whole-genome sequencing.
            seqmule pipeline -a s1.1.fastq -b s1.2.fastq -prefix genomeData -threads 12 -rg READGROUP -g -advanced misc/predefined_config/snap_freebayes.config

            #Input is multi-sample, paired-end exome. default pipeline 'bwa+gatk+samtools' will be used.
            seqmule pipeline -a sampleA.1.fq,sampleB.1.fq -b sampleA.2.fq,sampleB.2.fq -e -prefix sampleA,sampleB -capture default

            #Input is multi-sample, paired-end exome, with multi-sample variant calling
            seqmule pipeline -a sampleA.1.fq,sampleB.1.fq -b sampleA.2.fq,sampleB.2.fq -e -prefix sampleA,sampleB -ms

            #analysis on 3 BAM files for 3 samples. Output files will have same prefixes as BAM files.
            seqmule pipeline -bam 1.bam,2.bam,3.bam -e -capture default

            #same as above, except the 3 BAM files will be merged (as 1 sample)
            seqmule pipeline -bam 1.bam,2.bam,3.bam -e -merge -prefix sample -t 12

**Comment by yunfeiguo** [comment]
fixed in 077edeb Thanks!
